'use client';

import { Check, Coffee, Compass, Copy, Heart, Music2, Sparkles, Waves } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';

const openingLine = '嗨，我是 Vincent。比起一句话介绍自己，我做了一张小小的“人生地图”。如果你愿意，也想从你的故事里认识你。';

const branches = [
  { id: 'drive', icon: Compass, eyebrow: '01 / 我在做什么', title: '把事做好的人', copy: '在深圳创业，做德湃交易学院。9 年多交易经历与计量金融背景，让我习惯把复杂的事想清楚、做扎实。', notes: ['德湃交易学院', '教育培训行业 · CEO', '50 岁前，认真入世'], tone: 'border-[#b6d5ce] bg-[#edf8f5] text-[#186a5c]' },
  { id: 'fun', icon: Music2, eyebrow: '02 / 离开工作之后', title: '热烈，也能独处', copy: '足球、音乐、Livehouse、历史、美剧、滑雪和米其林餐厅，都能让我开心。也很珍惜一个人安静充电的时间。', notes: ['巴萨球迷', '会演奏乐器', '迪士尼是能量屋'], tone: 'border-[#e9c3a4] bg-[#fff4e8] text-[#9a531c]' },
  { id: 'love', icon: Heart, eyebrow: '03 / 我怎么谈恋爱', title: '直接、主动、浪漫', copy: '不喜欢猜谜或拐弯抹角。更喜欢真实地认识一个人：聊得来就见面，咖啡、好吃的、看展、散步都很好。', notes: ['不让女生倒贴成本', '见面比久聊更重要', '热情但保持独立'], tone: 'border-[#efb8c3] bg-[#fff0f3] text-[#a63d59]' },
  { id: 'future', icon: Waves, eyebrow: '04 / 想和谁同行', title: '认真谈一段恋爱', copy: '希望认识开朗、简单、直接又大方的人。同频的人一起闲逛、一起体验新鲜事，本身就是很好的生活。', notes: ['真诚优先', '愿意好好沟通', '慢慢走，也认真走'], tone: 'border-[#c6c4ee] bg-[#f2f1ff] text-[#57509b]' },
];

export default function Home() {
  const [active, setActive] = useState('drive');
  const [copied, setCopied] = useState(false);
  const selected = branches.find((branch) => branch.id === active) ?? branches[0];
  async function copyOpeningLine() { await navigator.clipboard.writeText(openingLine); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }

  return <main className="min-h-screen overflow-x-hidden bg-[#fcfbf7] text-[#19252a]"><div className="page-glow" aria-hidden="true" />
    <section className="relative mx-auto max-w-5xl px-5 pb-16 pt-7 sm:px-8 sm:pt-10">
      <header className="flex items-center justify-between"><span className="font-serif text-lg italic tracking-tight text-[#267869]">Vincent&apos;s map</span><span className="rounded-full border border-[#cfdfd9] bg-white/80 px-3 py-1 text-xs tracking-wide text-[#52706b]">认识一个真实的人</span></header>
      <section className="mt-12 rounded-[2.5rem] border border-[#d7e7e1] bg-white/70 px-6 py-10 text-center shadow-[0_18px_50px_rgba(28,69,61,.08)] sm:px-12 sm:py-14"><p className="mx-auto mb-4 flex w-fit items-center gap-2 text-sm font-medium text-[#277a6b]"><Sparkles className="size-4" /> 33 岁 · 深圳 · 创业者</p><h1 className="font-serif text-[clamp(3.5rem,8vw,6.3rem)] leading-[.86] tracking-[-0.065em] text-[#1c2d31]">你好，<br />我是 Vincent。</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-[#516469]">工作时我很认真，生活里也想留一点热烈。下面不是简历，是一张关于我怎样生活、怎样喜欢一个人的小地图。</p><div className="mt-7 flex flex-wrap justify-center gap-2 text-sm text-[#48615c]"><span className="rounded-full bg-white px-3 py-1.5 ring-1 ring-[#dfe9e5]">180 cm</span><span className="rounded-full bg-white px-3 py-1.5 ring-1 ring-[#dfe9e5]">ENTJ</span><span className="rounded-full bg-white px-3 py-1.5 ring-1 ring-[#dfe9e5]">来自广东深圳</span></div><div className="mx-auto mt-8 w-fit rounded-2xl bg-[#1e5049] px-5 py-3 text-sm text-white shadow-lg"><span className="block text-xs text-[#a9d8c9]">我最近的愿望</span>和喜欢的人一起去迪士尼。</div></section>
      <section className="mt-16" aria-label="Vincent 的人物思维导图"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#5e9a8e]">tap a node</p><h2 className="mt-2 font-serif text-3xl tracking-tight">我的人生思维导图</h2></div><p className="hidden max-w-xs text-right text-sm leading-6 text-[#70827f] sm:block">点一点四个节点，沿着这张抽象地图认识我。</p></div><div className="relative overflow-hidden rounded-[2.5rem] bg-[#f2f8f5] p-4 sm:p-8"><svg aria-hidden="true" viewBox="0 0 1000 520" className="pointer-events-none absolute inset-0 hidden h-full w-full md:block"><defs><linearGradient id="mind-line" x1="0" x2="1"><stop stopColor="#82bdb1" stopOpacity=".7" /><stop offset="1" stopColor="#e8b079" stopOpacity=".65" /></linearGradient></defs><path d="M500 260 C385 210 340 135 210 120 M500 260 C385 300 340 385 210 400 M500 260 C615 210 660 135 790 120 M500 260 C615 300 660 385 790 400" fill="none" stroke="url(#mind-line)" strokeDasharray="7 10" strokeWidth="2" /><circle cx="500" cy="260" r="105" fill="#d5ebe4" opacity=".42" /><circle cx="210" cy="120" r="10" fill="#8abdb2" /><circle cx="210" cy="400" r="10" fill="#e9b076" /><circle cx="790" cy="120" r="10" fill="#e6a2b4" /><circle cx="790" cy="400" r="10" fill="#aaa5dd" /></svg><div className="relative grid gap-4 md:grid-cols-[1fr_auto_1fr] md:items-center"><div className="grid gap-12 md:gap-32">{branches.slice(0, 2).map((branch) => <MapNode key={branch.id} branch={branch} active={active === branch.id} onClick={() => setActive(branch.id)} />)}</div><div className="order-first mx-auto flex size-40 flex-col items-center justify-center rounded-full border-[10px] border-white bg-[#1e5049] text-center text-white shadow-[0_18px_35px_rgba(31,80,73,.2)] md:order-none"><span className="font-serif text-3xl leading-none">V</span><span className="mt-1 text-xs text-[#b8ded3]">Vincent</span><span className="mt-3 size-2 rounded-full bg-[#f2c487]" /></div><div className="grid gap-12 md:gap-32">{branches.slice(2).map((branch) => <MapNode key={branch.id} branch={branch} active={active === branch.id} onClick={() => setActive(branch.id)} />)}</div></div></div><article className={`mt-5 rounded-[1.8rem] border p-6 transition-all sm:p-8 ${selected.tone}`}><selected.icon className="size-6" /><p className="mt-4 text-xs font-semibold tracking-[.14em]">{selected.eyebrow}</p><h3 className="mt-2 font-serif text-3xl tracking-tight">{selected.title}</h3><p className="mt-4 max-w-2xl leading-8 opacity-90">{selected.copy}</p><div className="mt-5 flex flex-wrap gap-2">{selected.notes.map((note) => <span key={note} className="rounded-full border border-current/20 bg-white/50 px-3 py-1.5 text-sm">{note}</span>)}</div></article></section>
      <section className="mt-12 rounded-[2rem] bg-[#1b3737] p-7 text-white shadow-[0_18px_45px_rgba(19,51,50,.2)] sm:p-10"><Coffee className="size-6 text-[#e8bf83]" /><h2 className="mt-4 font-serif text-3xl tracking-tight">不如，见一面？</h2><p className="mt-3 max-w-xl leading-7 text-[#c3d2cf]">我不太擅长把所有了解都留在聊天框里。找间咖啡馆，吃点好吃的，或者一起逛逛——面对面才更容易认识彼此。</p><Button onClick={copyOpeningLine} size="lg" className="mt-6 h-11 rounded-full bg-[#f2c487] px-5 text-[#263535] hover:bg-[#ffdaa4]">{copied ? <Check /> : <Copy />}{copied ? '已复制，来打个招呼吧' : '复制开场白'}</Button></section><footer className="pt-10 text-center text-xs tracking-wide text-[#8da09c]">认真生活，也认真等一场相遇。</footer>
    </section></main>;
}

function MapNode({ branch, active, onClick }: { branch: (typeof branches)[number]; active: boolean; onClick: () => void }) { const Icon = branch.icon; return <button type="button" onClick={onClick} className={`w-full rounded-3xl border p-5 text-left transition-all ${active ? `${branch.tone} shadow-md -translate-y-0.5` : 'border-[#dce8e4] bg-white/75 text-[#31474a] hover:border-[#8bb9af]'}`}><div className="flex items-start gap-3"><span className={`rounded-2xl p-2.5 ${active ? 'bg-white/65' : 'bg-[#edf5f2]'}`}><Icon className="size-5" /></span><span><span className="block text-xs font-semibold tracking-wide opacity-65">{branch.eyebrow}</span><span className="mt-1 block font-serif text-xl">{branch.title}</span></span></div></button>; }
